### ISSUE TITLE
Does not work with Android 5 because of included "libiomx.14.so"

### ISSUE THREAD

**Issue by sk2212** [mzafers/QtVlcMediaPlayer#1]
On Android 5 devices the library "libiomx.14.so" is not needed and building fails when including this library in "pro-file".

**Comment by mzafers** [comment]
Just add only libvlcjni.so file into apk.

**Comment by sk2212** [comment]
Do you think it is a good idea to remove all so files from the binary? For Android 4 they are needed, aren`t they?

**Comment by mzafers** [comment]
Actually, I'm testing it on Android 4.4.2 and I tested before on Android 4.1.2. There was no problem.

**Comment by sk2212** [comment]
Okay, will give it a try. Currently I am updating and recompile libvlcjni.so.

**Comment by IvanBelyakoff** [comment]
Pardon me guys, I never tested your lib exactly, but currently I have run issues with VLC on Android 5.0 due to the fact that libiomx.14.so still uses
`android::MemoryDealer::MemoryDealer(unsigned int, char const*)` (_ZN7android12MemoryDealerC1EjPKc)
instead of
`android::MemoryDealer::MemoryDealer(unsigned int, char const*,` **unsigned int**`)`
(_ZN7android12MemoryDealerC1EjPKc**j**) of libbinder.so, that is used on Android 5.0 (at least on my Samsung Galaxy tablet), so there is really an issue with compatibility.
